services:
  - type: web
    name: bot-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    runtime: python
    runtimeVersion: 3.11.9
